name: DogTag firmware

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/dogtag-build.yml
      - app/boards/shields/dogtag/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/zmkfirmware/zmk-build-arm:4.1
    steps:
      - uses: actions/checkout@v7
      - name: Initialize ZMK workspace
        run: |
          west init -l app
          west update --fetch-opt=--filter=tree:0
          west zephyr-export
      - name: Build DogTag
        run: west build -s app -p -b nice_nano@2.0.0/nrf52840/zmk -- -DSHIELD=dogtag
      - name: Upload DogTag firmware
        uses: actions/upload-artifact@v7
        with:
          name: dogtag-nice_nano_v2
          path: build/zephyr/zmk.uf2
          if-no-files-found: error
